const dataQuery = `{
    me {
      	artists{
          id
          name
          images{
            url
          }
          genres
      	}
        albums{
          album{
            id
            name
            images{
              url
            }
            artists{
              id
              name
            }
          }
        } 
        tracks {
          track{
            album{
              id
              name
            }
            artists{
              id
              name
            }
          }
        }
        top_tracks {
          album{
            id
            name
          }
          artists{
            id
            name
          }
        }
        top_artists{
          id
          name
          genres
          images{
            url
          }
        }
        playlists{
            tracks{
                track{
                    album{
                        id
                        name
                    }
                    artists{
                      id
                      name
                    }
                }
            }
        }
    }
}`;